WebBanHangMcv/Areas/admin/Controllers/AboutController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebBanHang_Common;
using WebBanHangMcv.Services.AboutService;
using WebQuanLyBanHangDtos;

namespace WebBanHangMcv.Areas.admin.Controllers
{
    public class AboutController : BaseController
    {
        private IAboutService _iaboutService;

        public AboutController(IAboutService _iaboutService)
        {
            this._iaboutService = _iaboutService;
        }

        // GET: admin/About
        [HttpGet]
        public ActionResult Index()
        {
            int Index = 0;
            var Data = _iaboutService.All<AboutDto>().ToList();
            foreach (var item in Data)
            {
                item.Stt += Index+1;
            }

            return View(Data);
        }

        [HttpGet]
        public ActionResult DanhSach()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetObjById(int id)
        {
            var data = _iaboutService.Find<AboutDto>(id);
            data.Ngaytao = data.CreatedDate.Value.ToString("dd/MM/yyyy");
            return Json(new JsonData<AboutDto>(200, data), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AddandEdit(AboutDto AboutDtos)
        {
            // Phần thêm mới
            try
            {
                if (AboutDtos.ID < 0)
                {
                    await _iaboutService.CreateAsync<AboutDto>(AboutDtos);
                    return Json(new JsonRespon(Mes: "Thêm mới thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    await _iaboutService.UpdateAsync<AboutDto>(AboutDtos, AboutDtos.ID);
                    return Json(new JsonRespon(Mes: "Chỉnh sửa thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            try
            {
                var DeleData = _iaboutService.Delete(id);
                return Json(new JsonRespon(Mes: "Xóa thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ChangCheck(int id)
        {
            var Data = _iaboutService.Find<AboutDto>(id);
            Data.Status = !Data.Status;
            int Res = _iaboutService.Update<AboutDto>(Data, id);
            if (Res > 0)
            {
                return Json(new JsonRespon(Mes: "Cập nhật thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonRespon(Mes: "Đã có lỗi sảy ra!", Status: 500), JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebBanHangMcv/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang_Common;
using WebBanHangMcv.Services.UserSrevices;
using WebQuanLyBanHangDtos;

namespace WebBanHangMcv.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        private IUserSercies _iUserService;
        public LoginController(IUserSercies _iUserService)
        {
            this._iUserService = _iUserService;
        }
        // GET: admin/Login
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult Loginfrom(UserLogin userLogin)
        {
            var Data = _iUserService.Login(userLogin);
            if (Data.Name !=null)
            {
                // Lưu Session
                Session["UserName"] = userLogin.UserName;
                return Json(new JsonRespon(Mes: "Đăng nhập thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonRespon(Mes: "Đăng nhập không thành công", Status: 500), JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Loguot()
        {
            Session.Clear();
            Session.Abandon();
            return Json(new JsonRespon(Mes: "Đăng xuất thành công", Status: 200), JsonRequestBehavior.AllowGet);
        }
        
    }
}

WebBanHangMcv/Areas/admin/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Đăng nhập quản trị</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/ImgFile/images/images.jpg" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/asset/login/css/style.css" rel="stylesheet" />

</head>
<body class="img js-fullheight" style="background-image: url(/asset/login/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Đăng nhập hệ thống</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        @*<h3 class="mb-4 text-center">Have an account?</h3>*@
                        <form action="#" class="signin-form">
                            <div class="form-group">
                                <input type="text" id="txtUserName" class="form-control" placeholder="Tên đăng nhập" required>
                            </div>
                            <div class="form-group">
                                <input id="password-field" type="password" class="form-control" placeholder="Mật khẩu" required>
                                <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="button" onclick="Sumitlogin()" class="form-control btn btn-primary submit px-3">Đăng nhập</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="#" style="color: #fff">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                        @*<p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
                        <div class="social d-flex text-center">
                            <a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
                            <a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
                        </div>*@
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/asset/login/js/jquery.min.js"></script>
    <script src="~/asset/login/js/popper.js"></script>
    <script src="~/asset/login/js/bootstrap.min.js"></script>
    <script src="~/asset/login/js/main.js"></script>
    <script>
        $(function () {

        });
        function get() {
            var Data = {
                UserName: $("#txtUserName").val(),
                Password: $("#password-field").val(),
                Name: null
            };
            return Data;
        };
        function Sumitlogin() {
            var Obj = get();
            $.ajax({
                url: '@Url.Action("Loginfrom", "Login")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ userLogin: Obj }),
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        if (data.Status == 200) {
                            window.location.href = "@Url.Action("DanhSach", "About")"
                        }
                        else {
                            alert("Tài khoản và mật khẩu không đúng!");
                        }
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }
             });
        }
    </script>
</body>
</html>