WebBanHangMcv/Areas/admin/Controllers/AboutController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebBanHang_Common;
using WebBanHangMcv.Services.AboutService;
using WebQuanLyBanHangDtos;

namespace WebBanHangMcv.Areas.admin.Controllers
{
    public class AboutController : BaseController
    {
        private IAboutService _iaboutService;

        public AboutController(IAboutService _iaboutService)
        {
            this._iaboutService = _iaboutService;
        }

        // GET: admin/About
        [HttpGet]
        public ActionResult Index()
        {
            int Index = 0;
            var Data = _iaboutService.All<AboutDto>().ToList();
            foreach (var item in Data)
            {
                item.Stt += Index+1;
            }

            return View(Data);
        }

        [HttpGet]
        public ActionResult DanhSach()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetObjById(int id)
        {
            var data = _iaboutService.Find<AboutDto>(id);
            data.Ngaytao = data.CreatedDate.Value.ToString("dd/MM/yyyy");
            return Json(new JsonData<AboutDto>(200, data), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AddandEdit(AboutDto AboutDtos)
        {
            // Phần thêm mới
            try
            {
                if (AboutDtos.ID < 0)
                {
                    await _iaboutService.CreateAsync<AboutDto>(AboutDtos);
                    return Json(new JsonRespon(Mes: "Thêm mới thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    await _iaboutService.UpdateAsync<AboutDto>(AboutDtos, AboutDtos.ID);
                    return Json(new JsonRespon(Mes: "Chỉnh sửa thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            try
            {
                var DeleData = _iaboutService.Delete(id);
                return Json(new JsonRespon(Mes: "Xóa thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult ChangCheck(int id)
        {
            var Data = _iaboutService.Find<AboutDto>(id);
            Data.Status = !Data.Status;
            int Res = _iaboutService.Update<AboutDto>(Data, id);
            if (Res > 0)
            {
                return Json(new JsonRespon(Mes: "Cập nhật thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonRespon(Mes: "Đã có lỗi sảy ra!", Status: 500), JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebBanHangMcv/Areas/admin/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebBanHang_Common;
using WebBanHangMcv.Services.UserSrevices;
using WebQuanLyBanHangDtos;

namespace WebBanHangMcv.Areas.admin.Controllers
{
    public class LoginController : Controller
    {
        private IUserSercies _iUserService;
        public LoginController(IUserSercies _iUserService)
        {
            this._iUserService = _iUserService;
        }
        // GET: admin/Login
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult Loginfrom(UserLogin userLogin)
        {
            var Data = _iUserService.Login(userLogin);
            if (Data.Name !=null)
            {
                // Lưu Session
                Session["UserName"] = userLogin.UserName;
                return Json(new JsonRespon(Mes: "Đăng nhập thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new JsonRespon(Mes: "Đăng nhập không thành công", Status: 500), JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Loguot()
        {
            Session.Clear();
            Session.Abandon();
            return Json(new JsonRespon(Mes: "Đăng xuất thành công", Status: 200), JsonRequestBehavior.AllowGet);
        }
        
    }
}

WebBanHangMcv/Areas/admin/Controllers/UserController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebBanHang_Common;
using WebBanHangMcv.Services.UserSrevices;
using WebQuanLyBanHangDtos;

namespace WebBanHangMcv.Areas.admin.Controllers
{
    public class UserController : BaseController
    {
        private IUserSercies _iUserService;

        public UserController(IUserSercies _iUserService)
        {
            this._iUserService = _iUserService;
        }

        // GET: admin/User
        [HttpGet]
        public ActionResult Index()
        {
            int Index = 0;
            var Data = _iUserService.All<UserDto>().ToList();
            foreach (var item in Data)
            {
                item.Stt += Index + 1;
            }

            return View(Data);
        }

        [HttpGet]
        public ActionResult DanhSach()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetObjById(int id)
        {
            var data = _iUserService.Find<UserDto>(id);
            data.Ngaytao = data.CreatedDate.Value.ToString("dd/MM/yyyy");
            return Json(new JsonData<UserDto>(200, data), JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<JsonResult> AddandEdit(UserDto UserDtos)
        {
            // Phần thêm mới
            try
            {
                if (UserDtos.ID < 0)
                {
                    UserDtos.Password = MD5Pasword.GetMD5(UserDtos.Password);
                    await _iUserService.CreateAsync<UserDto>(UserDtos);
                    return Json(new JsonRespon(Mes: "Thêm mới thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
                else
                {
                    await _iUserService.UpdateAsync<UserDto>(UserDtos, UserDtos.ID);
                    return Json(new JsonRespon(Mes: "Chỉnh sửa thành công", Status: 200), JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public JsonResult Delete(int id)
        {
            try
            {
                var DeleData = _iUserService.Delete(id);
                return Json(new JsonRespon(Mes: "Xóa thành công", Status: 200), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new JsonRespon(Mes: ex.Message, Status: 500), JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WebBanHangMcv/Areas/admin/Views/User/DanhSach.cshtml
@{
    ViewBag.Title = "DanhSach";
    Layout = "~/Areas/admin/Views/Shared/Layout.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Danh sách</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Người dùng</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        @*<div class="card-title">*@
                        <div class="row">
                            <div class="col-8">
                                <strong>Danh sách người dùng</strong>
                            </div>
                            <div class="col-4" style="text-align:right" ;>
                                <span class="btn btn-primary" onclick="Add()">Thêm mới</span>
                            </div>
                        </div>
                        @*</div>*@
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div id="tablerespon">

                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>

@*Modals thêm mới*@
<div class="modal fade" id="Modalnguoidung" tabindex="-1" role="dialog" aria-labelledby="mediumModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="mediumModalLabel">Medium Modal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="tile-body" id="tile-body">
                    <div class="form-group row">
                        <input type="hidden" id="isid" />
                        <label class="control-label col-md-2">Tên người dùng<span style="color:red">(*)</span></label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtName" placeholder="Nhập tên người dùng">
                        </div>
                        <label class="control-label col-md-2">Tên đăng nhập<span style="color:red">(*)</span></label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtUserName" placeholder="Nhập tên đăng nhập">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-2">Mật khẩu<span style="color:red">(*)</span></label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtPassword" placeholder="Nhập mật khẩu">
                        </div>
                        <label class="control-label col-md-2">Địa chỉ</label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtAddress">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="control-label col-md-2">Email</label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtEmail">
                        </div>
                        <label class="control-label col-md-2">Điện thoại</label>
                        <div class="col-md-4">
                            <input class="form-control" type="text" id="txtPhone">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="txtStatus" class="control-label col-md-3">Trạng thái hoạt động</label>
                        <div class="col-md-3">
                            <input class="form-check-input" type="checkbox" id="txtStatus">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnSave" onclick="save()">Confirm</button>
                <button type="button" class="btn btn-secondary" id="btndelete" data-dismiss="modal">Hủy</button>
            </div>
        </div>
    </div>
</div>
@*End Modal thêm mới*@
@section scripts {
    <script type="text/javascript">
        $(function () {
            LoadTable();
        });
        function LoadTable() {
            $.ajax({
                url: '@Url.Action("Index", "User")',
                type: 'GET',
            }).done(function (data) {
                $('#tablerespon').html(data);
                $("#tablerepoin").DataTable({
                    "responsive": true, "lengthChange": false, "autoWidth": false,
                    "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
                }).buttons().container().appendTo('#tablerepoin_wrapper .col-md-6:eq(0)');

            });
        };

        function Reset() {
            $('#txtUserName').val("");
            $('#txtPassword').val("");
            $('#txtName').val("");
            $('#txtAddress').val("");
            $('#txtEmail').val("");
            $('#txtPhone').val("");
            $("#txtStatus").prop('checked', false);

            ClearError('#txtten');
            $("#btnSave").text("Lưu lại");
            $('#tile-body').nextAll(".spanError").remove();
        };
        function validate() {
            FormModalIsValid = true;
            ValidateRequireControl('#txtUserName', 'Bạn phải nhập trường này!');
            ValidateRequireControlMaxLength("#txtUserName", "Bạn không được nhập quá tên chủ đầu tư quá 256 ký tự", 256);
            ValidateRequireControl('#txtPassword', 'Bạn phải nhập trường này!');
            ValidateRequireControlMaxLength("#txtPassword", "Bạn không được nhập quá tên chủ đầu tư quá 256 ký tự", 256);
            ValidateRequireControl('#txtName', 'Bạn phải nhập trường này!');
            ValidateRequireControlMaxLength("#txtName", "Bạn không được nhập quá tên chủ đầu tư quá 256 ký tự", 256);
        };
        function Get() {
            var Data = {
                ID: $("#isid").val(),
                UserName: $('#txtUserName').val(),
                Password: $('#txtPassword').val(),
                Name: $('#txtName').val(),
                Address: $('#txtAddress').val(),
                Email: $('#txtEmail').val(),
                Phone: $('#txtPhone').val(),
                CreatedDate: new Date(),
                ModifiedDate: new Date(),
            };
            return Data;
        };
        function set(Obj) {
            $("#isid").val(Obj.ID);
            $('#txtUserName').val(Obj.UserName);
            $('#txtPassword').val(Obj.Password);
            $('#txtName').val(Obj.Name);
            $('#txtAddress').val(Obj.Address);
            $("#txtEmail").val(Obj.Email);
            $('#txtPhone').val(Obj.Phone);
        };
        function Add() {
            Reset();
            $("#isid").val("-1");
            $('#tile-body').nextAll(".spanError").remove()
            $('#mediumModalLabel').html('Thêm mới người dùng')
            $('#btnSave').html('Thêm mới')
            $("#Modalnguoidung").modal({ backdrop: "static" })
        };
        function save() {
        var Obj = Get();
            validate()
            if (FormModalIsValid) {
                $.ajax({
                    url: '@Url.Action("AddandEdit", "User")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ UserDtos: Obj }),
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        if (data.Status == 200) {
                            toastr.success(data.Mes);
                            $("#Modalnguoidung").modal("hide")
                            LoadTable();
                        }
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }
                });
            }
        };
        function Edit(id) {
                $.ajax({
                    url: '@Url.Action("GetObjById", "User")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ id: id }),
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        console.log(data.Data);
                        if (data.Status == 200) {
                            $('#btnSave').html('Cập nhật');
                            $('#textthemmoi').html('Chỉnh sửa');
                            $('#textthemmoinho').html('Chỉnh sửa');
                            $('#mediumModalLabel').html('Chỉnh sửa')
                            //hiện modal
                            $("#Modalnguoidung").modal({ backdrop: "static" })

                            set(data.Data);
                        }
                    },
                    error: function (xhr) {
                        alert('error');
                    }
                });
        };
        function Delete(id) {
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success',
                    cancelButton: 'btn btn-danger'
                },
                buttonsStyling: false
            })
            swalWithBootstrapButtons.fire({
                title: 'Bạn có chắc không?',
                text: "Bạn sẽ không thể khôi phục được dữ liệu!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Có, xóa nó!',
                cancelButtonText: 'Không, hủy bỏ!',
                reverseButtons: true
            }).then((result) => {
                if (result.isConfirmed) {
                     $.ajax({
                            url: "@Url.Action("Delete", "User")",
                            type: "GET",
                            data: {id:id},
                            cache: false,
                         success: function (data) {
                             LoadTable();
                                swalWithBootstrapButtons.fire(
                                    'Đã xóa!',
                                    'Tệp của bạn đã bị xóa.',
                                    'success'
                                )
                            },
                            error: function (xhr) {
                                Swal.fire(xhr);
                            }
                     });
                } else if (
                    /* Read more about handling dismissals below */
                    result.dismiss === Swal.DismissReason.cancel
                ) {
                    swalWithBootstrapButtons.fire(
                        'Đã hủy',
                        'Tệp của bạn an toàn!',
                        'error'
                    )
                }
            })
        };
        function ChangCheck(id) {
            $.ajax({
                 url: "@Url.Action("ChangCheck", "User")",
                 type: "POST",
                 data: {id:id},
                 cache: false,
                 success: function (data) {
                     toastr.success(data.Mes);
                     LoadTable();
                 },
                 error: function (xhr) {
                     Swal.fire(xhr);
                 }});
        }
    </script>
}

WebBanHangMcv/Areas/admin/Views/User/Index.cshtml
@model IEnumerable<WebQuanLyBanHangDtos.UserDto>
@{
    ViewBag.Title = "DanhSach";
    Layout = null;
}
<table id="tablerepoin" class="table table-bordered">
    <thead>
        <tr class="text-center">
            <th>Stt</th>
            <th>Tên đăng nhập</th>
            <th>Số điện thoại</th>
            <th>Email</th>
            <th>Địa chỉ</th>
            <th>Trạng thái</th>
            <th>Chức năng</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">@item.Stt</td>
                <td>@item.UserName</td>
                <td>@item.Phone</td>
                <td>@item.Email</td>
                <td>@item.Address</td>
                <td class="text-center">
                    @if (item.Status.HasValue)
                    {
                        if (item.Status.Value)
                        {
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked onchange="ChangCheck(@item.ID)">
                        }
                        else
                        {
                            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" onchange="ChangCheck(@item.ID)">
                        }
                    }
                </td>
                <td class="text-center">
                    <a title="Sửa thông tin" onclick="Edit(@item.ID)" class="btn btn-sm btn-primary" href="#"><i class="fa fa-edit"></i></a>
                    &nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp;
                    <a title="Xóa bản ghi" onclick="Delete(@item.ID)" class="btn btn-sm btn-danger" href="#"><i class="fa fa-fw fa-trash"></i></a>
                </td>
            </tr>
        }

    </tbody>
</table>

WebBanHangMcv/Areas/admin/Views/User/Login.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Đăng nhập quản trị</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="~/ImgFile/images/images.jpg" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/asset/login/css/style.css" rel="stylesheet" />

</head>
<body class="img js-fullheight" style="background-image: url(/asset/login/images/bg.jpg);">
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Đăng nhập hệ thống</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-6 col-lg-4">
                    <div class="login-wrap p-0">
                        @*<h3 class="mb-4 text-center">Have an account?</h3>*@
                        <form action="#" class="signin-form">
                            <div class="form-group">
                                <input type="text" id="txtUserName" class="form-control" placeholder="Tên đăng nhập" required>
                            </div>
                            <div class="form-group">
                                <input id="password-field" type="password" class="form-control" placeholder="Mật khẩu" required>
                                <span toggle="#password-field" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                            </div>
                            <div class="form-group">
                                <button type="button" onclick="Sumitlogin()" class="form-control btn btn-primary submit px-3">Đăng nhập</button>
                            </div>
                            <div class="form-group d-md-flex">
                                <div class="w-50">
                                    <label class="checkbox-wrap checkbox-primary">
                                        Remember Me
                                        <input type="checkbox" checked>
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                <div class="w-50 text-md-right">
                                    <a href="#" style="color: #fff">Forgot Password</a>
                                </div>
                            </div>
                        </form>
                        @*<p class="w-100 text-center">&mdash; Or Sign In With &mdash;</p>
                            <div class="social d-flex text-center">
                                <a href="#" class="px-2 py-2 mr-md-1 rounded"><span class="ion-logo-facebook mr-2"></span> Facebook</a>
                                <a href="#" class="px-2 py-2 ml-md-1 rounded"><span class="ion-logo-twitter mr-2"></span> Twitter</a>
                            </div>*@
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/asset/login/js/jquery.min.js"></script>
    <script src="~/asset/login/js/popper.js"></script>
    <script src="~/asset/login/js/bootstrap.min.js"></script>
    <script src="~/asset/login/js/main.js"></script>
    <script>
        $(function () {

        });
        function get() {
            var Data = {
                UserName: $("#txtUserName").val(),
                Password: $("#password-field").val(),
                Name: null
            };
            return Data;
        };
        function Sumitlogin() {
            var Obj = get();
            $.ajax({
                    url: '@Url.Action("Loginfrom", "User")',
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ userLogin: Obj }),
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        if (data.Status == 200) {
                            //toastr.success(data.Mes);
                            window.location.href = "@Url.Action("DanhSach", "About")"
                        }
                    },
                    error: function (xhr) {
                        alert(xhr);
                    }
             });
        }
    </script>
</body>
</html>